### ISSUE TITLE
[REQUEST][HELP] Debug setuP

### ISSUE THREAD

**Issue by EINBOX** [wswebcreation/swiping-your-way-through-appium#3]
Sir, 
I am kindly requesting how can I run in debug mode using WDIO runner, I tried couple of soups and did google but not helped much
without debugging ,its taking lot of time to write or updating code , save me my time please

really am struggling running wdio runner in debug mode 

Placed request on Gitter as well but not getting response ..its been over. a month …if I can't find solution for debug setup..its night mare for me to develop the code

IDE: intelliJ
please consider me as new to wdio 

Thanks In Advance

**Comment by wswebcreation** [comment]
I haven't used the debug mode yet, so can't help you with that. Please also don't ask those questions here if they are not related to this set up
